on:
  push:
    branches:
      - '*'
jobs:
  Job:
    runs-on: ubuntu-latest
    env:
      GHP_USER: ${{ secrets.GHP_USER }}
      GHP_PASSWORD: ${{ secrets.GHP_PASSWORD }}
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Get User
        run: echo "AUTHOR_EMAIL=$(git show -s --format='%ae')" >>$GITHUB_ENV

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: corretto
          java-version: "8"

      - name: Tag
        run: ./gradlew tag

      - name: Build
        run: ./gradlew clean assemble

      - name: Publish
        run: ./gradlew publish

      - name: Notify
        if: always()
        continue-on-error: true
        uses: slackapi/slack-github-action@v1.23.0
        with:
          payload: |
            {
              "emoji": "${{ job.status == 'success' && ':large_green_circle:' || ':red_circle:' }}",
              "message": "${{ job.status }}",
              "url": "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}",
              "email": "${{ env.AUTHOR_EMAIL }}"
            }
